GET http://localhost:5000/api/electricity
###
GET http://localhost:5000/api/electricity/3

###
POST http://localhost:5000/api/electricity HTTP/1.1
content-type: application/json

{
  "month": "2022-06-15",
  "usage": "1200.000",
  "cost": "200.00"
}

###

PUT http://localhost:5000/api/electricity HTTP/1.1
content-type: application/json

{
  "id": 6,
  "month": "2022-06-15",
  "usage": "1300.000",
  "cost": "1200.00"
}

###

DELETE http://localhost:5000/api/electricity/6

###